# Generated by Django 3.2.2 on 2021-05-10 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDesc', models.TextField()),
                ('productPrice', models.FloatField()),
                ('productDisp', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceStatus', models.IntegerField(choices=[(-1, 'Not Started'), (0, 'Unconfirmed'), (1, 'Partially Confirmed'), (2, 'Confirmed')], default=-1)),
                ('invoiceOrderId', models.CharField(max_length=250)),
                ('invoiceAddress', models.CharField(blank=True, default='', max_length=250)),
                ('invoiceBtcValue', models.IntegerField(blank=True, null=True)),
                ('invoiceReceived', models.IntegerField(blank=True, null=True)),
                ('invoiceTxid', models.CharField(blank=True, max_length=250, null=True)),
                ('invoiceRbf', models.IntegerField(blank=True, null=True)),
                ('invoiceCreatedAt', models.DateField(auto_now=True)),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
