# Generated by Django 3.2.2 on 2021-05-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceAddress',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
