# Generated by Django 3.2.2 on 2021-05-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoice_invoiceaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceAddress',
        ),
    ]
