# Generated by Django 3.2.2 on 2021-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_invoice_invoiceaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceAddress',
            field=models.CharField(default='', max_length=250),
        ),
    ]
